services:
  squid-manager:
    image: ghcr.io/nodelibdev/squid-manager:latest
    # build: .
    container_name: squid-manager
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /etc/squid/allowed_domains.txt:/data/allowed_domains.txt
      - /etc/squid/allowed_ips.txt:/data/allowed_ips.txt
      - /tmp/squid-reload-pipe:/tmp/squid-reload-pipe
    environment:
      - AUTH_TOKEN=your_token_here